name: idrac_ctl

channels:
  - defaults
  - conda-forge

dependencies:
  - python => 3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pygments
      - tqdm
      - requests
  - cmake >= 3.11
  - make
  - cxx-compiler
  - gxx = 10
  - numpy
  - matplotlib
  - pyyaml
  - tqdm